[meta]
author    = "JailMan"
name      = "RGBCar"
version   = "2.0.1"
category  = "Fun"

[script]
dependencies = [ "VehicleState" ]
optional_dependencies = [ "CurrentEffects" ]
exports = [ "Export.as" ]